### ISSUE TITLE
Instead of creating rchitect why not contribute to rpy2 to add needed features?

### ISSUE THREAD

**Issue by hermidalc** [randy3k/rapi#18]
Just out of of interest, instead of creating `rchitect` and reinventing yet another python/R interface, why not instead spend the effort you are already spending to contribute to `rpy2` to add the features you need for `radian`? `rpy2` is open-source, on Github, very mature, and frankly it's a wonderful library (I use it almost every day).

**Comment by randy3k** [comment]
We and rpy2 has different goals. I have explained it in the readme.

**Comment by hermidalc** [comment]
> We and rpy2 has different goals. I have explained it in the readme.

The README doesn't say anything more than this

> rpy2 was not suitable because it is missing some key features for running the R REPL

I had already read that before writing this OP, that's what I meant before, why not spend the effort contributing to `rpy2` in order to add the missing features you need for running the R REPL?

**Comment by randy3k** [comment]
It is a long story. At first, rchitect was developed with rpy2 was still in 2.x. With that version of rpy2, there were a few issues

1. rpy2 needsed to be compiled against R shared library, it means that users cannot switch between versions of R.
2. ryp2 didn't work on Windows.  I believe even the current version of rpy2 doesn't work very well on Windows.
3. it is not possible to ship with a precompiled wheel with that version rpy2 because again, it needed to compiled against R shared library.

It was virtually not possible to use rpy2 to run radian because it requires users to be able to figure out how to compile against the R shared library. Not to mention the support on Windows. So basically we need to dynamically load the R shared library instead of building against it. I had no other options but to start writing everything from scratch.

The rpy2 version 3.x changes the way that the R library is loaded, theoretically it is possible to use rpy2 for radian now. But I have already developed rchitect at that point, it doesn't make sense to switch to rpy2 then.

**Comment by hermidalc** [comment]
> It is a long story. At first, rchitect was developed with rpy2 was still in 2.x. With that version of rpy2, there were a few issues
> 
> 1. rpy2 needsed to be compiled against R shared library, it means that users cannot switch between versions of R.
> 2. ryp2 didn't work on Windows.  I believe even the current version of rpy2 doesn't work very well on Windows.
> 3. it is not possible to ship with a precompiled wheel with that version rpy2 because again, it needed to compiled against R shared library.
> 
> It was virtually not possible to use rpy2 to run radian because it requires users to be able to figure out how to compile against the R shared library. Not to mention the support on Windows. So basically we need to dynamically load the R shared library instead of building against it. I had no other options but to start writing everything from scratch.
> 
> The rpy2 version 3.x changes the way that the R library is loaded, theoretically it is possible to use rpy2 for radian now. But I have already developed rchitect at that point, it doesn't make sense to switch to rpy2 then.

Thanks for the explanation of your rationale. Makes a lot of sense and sorry didn’t realize you started developing this long ago.
